### ISSUE TITLE
Configuration

### ISSUE THREAD

**Issue by ClapperYT** [srhinos/rsb#2]
Is there a way that you could make a video tutorial on how to set this bot up?

I am in the R6 Discord and I love this bot, but I have only bothered to learn JS. 

If you could make a video that explains how to set up the bot for those of us not so "inclined" in python that would be very beneficial. (or at least try telling me what to change so that I can make it work)

**Comment by Ullizzzz** [comment]
As this was my first ever python bot it's not that hard to get going when you find the right setup.
I use Python 3.6 and Discord Rewrite, rest can be seen in top of bot.py.

Mostly you need to change ID for channels to get it going.

**Comment by ClapperYT** [comment]
that would be done in constants.py correct?

what can I change in this file without it breaking the entire program lol?

also, I don't really use GitHub that much, if we could talk on Twitter or Discord that would be much better for me personally.

Twitter: @ClapperYT
Discord: @ClapperYT#7748

**Comment by farnoods** [comment]
your code has issues man

```Traceback (most recent call last):
File "run.py", line 5, in <module>
R6Bot().run()
File "/app/r6bot/bot.py", line 90, in __init__
self.user_http = HTTPClient(None, proxy=None, proxy_auth=None, loop=asyncio.get_event_loop())
TypeError: __init__() got an unexpected keyword argument 'proxy'
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7fb11009fb70>
Process exited with status 1
```
i ran the run.py file, i have already configured BOT_TOKEN in the creds.py, and i have python 3.6.0

**Comment by srhinos** [comment]
idk whats goin on here but this isn't a valid issue
